/*
 Task Name ---> NUMBER GUESSING GAME 

    Task Description ---> 
    
    --->>> The fun and easy project Guess the Number is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:

    1.    The system generates a random number from a given range, say 1 to 100.

    2.   The user is prompted to enter their given number in a displayed dialogue box.

    3.    The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.

    4.    The game continues under the user guessing the number.

    --->>> You can also incorporate further details as:

    1.    Limiting the number of attempts.

    2.    Adding more rounds.

    3.    Displaying score.

    4.    Giving points based on the number of attempts.

    Topics : Java Core Concepts :
    1.Data Types
    2.Variables
    3.Strings
    4.Conditional Statements
    5.Random Generators
 */

import java.util.Random;
import java.util.Scanner;

public class GuessTheNumber 
{
    public static void main(String[] args)
    {
        int minRange = 1;
        int maxRange = 100;
        int maxAttempts = 8;
        int score = 0;
        int rounds = 0;

        boolean playAgain = true;
        Scanner scanner = new Scanner(System.in);

        while (playAgain) 
        {
            System.out.println("===== Round " + (rounds + 1) + " =====");
            int randomNumber = generateRandomNumber(minRange, maxRange);
            int attempts = 0;

            boolean guessedCorrectly = false;
            while (!guessedCorrectly && attempts < maxAttempts)
            {
                System.out.print("Guess the number between " + minRange + " and " + maxRange + ": ");
                int guess = scanner.nextInt();
                attempts++;

                if (guess == randomNumber) 
                {
                    guessedCorrectly = true;
                    int roundScore = maxAttempts - attempts + 1;
                    score += roundScore;
                    System.out.println("Congratulations! You guessed the correct number in " + attempts + " attempts.");
                    System.out.println("Round Score: " + roundScore);
                } 
                else if (guess < randomNumber) 
                {
                    System.out.println("Too low! Try again.");
                } else 
                {
                    System.out.println("Too high! Try again.");
                }
            }

            if (!guessedCorrectly) 
            {
                System.out.println("You ran out of attempts. The number was: " + randomNumber);
            }

            rounds++;
            System.out.print("Play again? (yes/no): ");
            String playAgainResponse = scanner.next();
            playAgain = playAgainResponse.equalsIgnoreCase("yes");
            System.out.println();
        }

        System.out.println("Game Over!");
        System.out.println("Total Rounds: " + rounds);
        System.out.println("Total Score: " + score);
    }

    private static int generateRandomNumber(int min, int max) 
    {
        Random random = new Random();
        return random.nextInt(max - min + 1) + min;
    }
}
